[package]
name = "home-info-display"
version = "0.1.0"
authors = ["rschwalk <rschwalk@rschwalk.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.34.0"
default-features = false
features = ["ttf"]